{
 "title": "Sample App – SRE Observability Dashboard",
 "time": { "from": "2026-02-08T07:46:27.617Z", "to": "2026-02-08T08:46:27.617Z" },
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(sample_app_requests_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Add Latency Panel (P95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum(rate(sample_app_request_latency_seconds_bucket[5m])) by (le)\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate Panel (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(sample_app_requests_total[5m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}